chore: update to cosign v3 and don't break things (#243)
This is the way to workaround the upstream issues I linked below.

We need `--use-signing-config=false` or else we are getting the
following erorr:

```
Error: must provide --new-bundle-format or --bundle where applicable
with --signing-config or --use-signing-config error during command
```